use chrono::{DateTime, Utc};
use serde_json::Value;

#[derive(Clone)]
pub(crate) struct NormalizedTimelineOrder {
    pub(crate) order_id: String,
    pub(crate) flight_id: String,
    pub(crate) flight_no: String,
    pub(crate) task_type: String,
    pub(crate) task_type_name: String,
    pub(crate) status: String,
    pub(crate) start_time: DateTime<Utc>,
    pub(crate) end_time: DateTime<Utc>,
    pub(crate) planned_start_time: Option<DateTime<Utc>>,
    pub(crate) planned_end_time: Option<DateTime<Utc>>,
    pub(crate) actual_start_time: Option<DateTime<Utc>>,
    pub(crate) actual_end_time: Option<DateTime<Utc>>,
    pub(crate) estimated_completion_time: Option<DateTime<Utc>>,
    pub(crate) estimated_completion_reported_by: Option<String>,
    pub(crate) estimated_completion_reported_at: Option<DateTime<Utc>>,
    pub(crate) estimated_completion_note: Option<String>,
    pub(crate) effective_end_source: String,
    pub(crate) individual_user_id: Option<String>,
    pub(crate) individual_username: Option<String>,
    pub(crate) stand_id: Option<String>,
    pub(crate) stand_code: Option<String>,
    pub(crate) gate: Option<String>,
    pub(crate) terminal: Option<String>,
    pub(crate) source: String,
    pub(crate) dispatch_type: String,
    pub(crate) members: Vec<Value>,
    pub(crate) equipments: Vec<Value>,
    pub(crate) member_names: Vec<String>,
    pub(crate) equipment_codes: Vec<String>,
    pub(crate) display_label: String,
}

#[derive(Clone)]
pub(crate) struct TimelineItem {
    pub(crate) id: String,
    pub(crate) order_id: Option<String>,
    pub(crate) flight_id: String,
    pub(crate) flight_no: String,
    pub(crate) task_type: Option<String>,
    pub(crate) task_type_name: String,
    pub(crate) status: String,
    pub(crate) start_time: DateTime<Utc>,
    pub(crate) end_time: DateTime<Utc>,
    pub(crate) planned_start_time: Option<DateTime<Utc>>,
    pub(crate) planned_end_time: Option<DateTime<Utc>>,
    pub(crate) actual_start_time: Option<DateTime<Utc>>,
    pub(crate) actual_end_time: Option<DateTime<Utc>>,
    pub(crate) estimated_completion_time: Option<DateTime<Utc>>,
    pub(crate) estimated_completion_reported_by: Option<String>,
    pub(crate) estimated_completion_reported_at: Option<DateTime<Utc>>,
    pub(crate) estimated_completion_note: Option<String>,
    pub(crate) effective_end_source: String,
    pub(crate) lane_key: String,
    pub(crate) lane_label: String,
    pub(crate) lane_index: usize,
    pub(crate) lane_subtrack: usize,
    pub(crate) lane_subtrack_count: usize,
    pub(crate) individual_user_id: Option<String>,
    pub(crate) individual_username: Option<String>,
    pub(crate) stand_id: Option<String>,
    pub(crate) stand_code: Option<String>,
    pub(crate) gate: Option<String>,
    pub(crate) terminal: Option<String>,
    pub(crate) source: String,
    pub(crate) dispatch_type: String,
    pub(crate) members: Vec<Value>,
    pub(crate) equipments: Vec<Value>,
    pub(crate) member_names: Vec<String>,
    pub(crate) equipment_codes: Vec<String>,
    pub(crate) label: String,
    pub(crate) is_flight_summary: bool,
    pub(crate) related_order_ids: Vec<String>,
    pub(crate) related_orders: Vec<Value>,
    pub(crate) focus_user_id: Option<String>,
    pub(crate) focus_user_name: Option<String>,
    pub(crate) focus_equipment_id: Option<String>,
    pub(crate) focus_equipment_code: Option<String>,
}

#[derive(Clone)]
pub(crate) struct TimelineLane {
    pub(crate) id: String,
    pub(crate) label: String,
    pub(crate) index: usize,
    pub(crate) subtrack_count: usize,
    pub(crate) item_count: usize,
}
