services:
  postgres:
    ports:
      - "127.0.0.1:${HOST_POSTGRES_PORT:-5432}:5432"

  redis:
    ports:
      - "127.0.0.1:${HOST_REDIS_PORT:-6379}:6379"

  flowable:
    ports:
      - "127.0.0.1:${HOST_FLOWABLE_PORT:-8082}:8080"
