-- 迁移：补齐细粒度 resource.action 权限，并为旧粗粒度角色做兼容回填
-- 日期：2026-04-22
-- 说明：
-- 1. 新增 V2 细粒度权限种子
-- 2. 将既有 coarse-grained 角色授权映射为新的 resource.action 授权
-- 3. 更新系统 permission_templates，保持新旧权限并存，便于平滑迁移

INSERT INTO permissions (id, name, description, is_active)
VALUES
    ('perm_flight_read_v2', 'flight.read', '查看航班信息', TRUE),
    ('perm_flight_update_v2', 'flight.update', '更新航班信息', TRUE),
    ('perm_flight_timeline_v2', 'flight.timeline_edit', '编辑航班时间线', TRUE),
    ('perm_flight_import_v2', 'flight.import_commit', '提交航班导入', TRUE),
    ('perm_flight_report_v2', 'flight.report_generate', '生成航班动态报表', TRUE),
    ('perm_bc_create_v2', 'business_case.create', '创建业务事项', TRUE),
    ('perm_bc_read_v2', 'business_case.read', '查看业务事项', TRUE),
    ('perm_bc_append_v2', 'business_case.append', '追加业务事项信息', TRUE),
    ('perm_bc_update_v2', 'business_case.update', '更新业务事项', TRUE),
    ('perm_bc_status_v2', 'business_case.status_transition', '推进业务事项状态', TRUE),
    ('perm_bc_delete_v2', 'business_case.delete', '删除业务事项', TRUE),
    ('perm_wr_start_v2', 'workflow_run.start', '发起业务事项流程实例', TRUE),
    ('perm_wr_read_v2', 'workflow_run.read', '查看流程运行实例', TRUE),
    ('perm_wr_act_v2', 'workflow_run.act', '执行流程人工节点动作', TRUE),
    ('perm_wf_def_read2', 'workflow_definition.read', '查看流程定义', TRUE),
    ('perm_wf_def_edit2', 'workflow_definition.edit', '编辑流程定义', TRUE),
    ('perm_wf_def_pub2', 'workflow_definition.publish', '发布流程定义', TRUE),
    ('perm_wf_def_depr2', 'workflow_definition.deprecate', '停用流程定义', TRUE),
    ('perm_auto_notify2', 'automation.notify_send', '在流程中使用自动通知能力', TRUE),
    ('perm_auto_dispatch2', 'automation.dispatch_create', '在流程中使用自动派工能力', TRUE),
    ('perm_auto_case_ok2', 'automation.business_case_complete', '在流程中自动完成业务事项', TRUE),
    ('perm_auto_case_ng2', 'automation.business_case_fail', '在流程中自动失败业务事项', TRUE),
    ('perm_auto_http2', 'automation.external_call', '在流程中调用外部接口', TRUE),
    ('perm_auto_ai2', 'automation.ai_execute', '在流程中执行 AI 自动化能力', TRUE),
    ('perm_do_read_v2', 'dispatch_order.read', '查看派工单', TRUE),
    ('perm_do_create_v2', 'dispatch_order.create', '创建派工单', TRUE),
    ('perm_do_update_v2', 'dispatch_order.update', '更新派工单', TRUE),
    ('perm_do_publish_v2', 'dispatch_order.publish', '发布派工单', TRUE),
    ('perm_do_cancel_v2', 'dispatch_order.cancel', '取消派工单', TRUE),
    ('perm_dc_read_v2', 'dispatch_catalog.read', '查看派工资源目录', TRUE),
    ('perm_dc_edit_v2', 'dispatch_catalog.edit', '编辑派工资源目录', TRUE),
    ('perm_sh_read_v2', 'shift_handover.read', '查看交接班', TRUE),
    ('perm_sh_create_v2', 'shift_handover.create', '创建交接班', TRUE),
    ('perm_sh_submit_v2', 'shift_handover.submit', '提交交接班', TRUE),
    ('perm_sh_ack_v2', 'shift_handover.ack', '确认交接班', TRUE),
    ('perm_notif_read2', 'notification.read', '查看通知', TRUE),
    ('perm_notif_send2', 'notification.send', '发送通知', TRUE),
    ('perm_notif_rcpt_r2', 'notification.receipt_read', '查看通知回执', TRUE),
    ('perm_notif_rcpt_m2', 'notification.receipt_manage', '管理通知回执', TRUE),
    ('perm_auth_role_r2', 'auth_role.read', '查看角色定义', TRUE),
    ('perm_auth_role_e2', 'auth_role.edit', '编辑角色定义', TRUE),
    ('perm_auth_tpl_r2', 'auth_permission_template.read', '查看权限模板', TRUE),
    ('perm_auth_tpl_e2', 'auth_permission_template.edit', '编辑权限模板', TRUE),
    ('perm_user_admin_r2', 'user_admin.read', '查看用户管理数据', TRUE),
    ('perm_user_admin_e2', 'user_admin.edit', '编辑用户管理数据', TRUE),
    ('perm_sys_cfg_r2', 'system.config_read', '查看系统配置', TRUE),
    ('perm_sys_cfg_w2', 'system.config_write', '编辑系统配置', TRUE),
    ('perm_sys_ops_admin2', 'system.ops_admin', '执行系统运维管理操作', TRUE)
ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    is_active = TRUE,
    updated_at = CURRENT_TIMESTAMP;

WITH legacy_permission_mapping(legacy_name, granular_name) AS (
    VALUES
        ('flight:read', 'flight.read'),
        ('flight:read', 'business_case.read'),
        ('flight:read', 'workflow_run.read'),
        ('flight:manage', 'flight.read'),
        ('flight:manage', 'flight.update'),
        ('flight:manage', 'flight.timeline_edit'),
        ('flight:manage', 'flight.import_commit'),
        ('flight:manage', 'flight.report_generate'),
        ('flight:manage', 'business_case.create'),
        ('flight:manage', 'business_case.read'),
        ('flight:manage', 'business_case.append'),
        ('flight:manage', 'business_case.update'),
        ('flight:manage', 'business_case.status_transition'),
        ('flight:manage', 'workflow_run.start'),
        ('flight:manage', 'workflow_run.read'),
        ('flight:manage', 'workflow_run.act'),
        ('dispatch:view', 'dispatch_order.read'),
        ('dispatch:view', 'dispatch_catalog.read'),
        ('dispatch:view', 'shift_handover.read'),
        ('dispatch:view', 'notification.read'),
        ('dispatch:view', 'notification.receipt_read'),
        ('dispatch:manage', 'dispatch_order.read'),
        ('dispatch:manage', 'dispatch_order.create'),
        ('dispatch:manage', 'dispatch_order.update'),
        ('dispatch:manage', 'dispatch_order.publish'),
        ('dispatch:manage', 'dispatch_order.cancel'),
        ('dispatch:manage', 'dispatch_catalog.read'),
        ('dispatch:manage', 'dispatch_catalog.edit'),
        ('dispatch:manage', 'shift_handover.read'),
        ('dispatch:manage', 'shift_handover.create'),
        ('dispatch:manage', 'shift_handover.submit'),
        ('dispatch:manage', 'shift_handover.ack'),
        ('dispatch:manage', 'notification.read'),
        ('dispatch:manage', 'notification.send'),
        ('dispatch:manage', 'notification.receipt_read'),
        ('dispatch:manage', 'notification.receipt_manage'),
        ('flowable:read', 'workflow_definition.read'),
        ('flowable:read', 'workflow_run.read'),
        ('flowable:manage', 'workflow_definition.read'),
        ('flowable:manage', 'workflow_definition.edit'),
        ('flowable:manage', 'workflow_definition.publish'),
        ('flowable:manage', 'workflow_definition.deprecate'),
        ('user:read', 'user_admin.read'),
        ('user:create', 'user_admin.edit'),
        ('user:update', 'user_admin.edit'),
        ('user:delete', 'user_admin.edit'),
        ('role:read', 'auth_role.read'),
        ('role:create', 'auth_role.edit'),
        ('role:update', 'auth_role.edit'),
        ('role:delete', 'auth_role.edit'),
        ('auth:view', 'user_admin.read'),
        ('auth:view', 'auth_role.read'),
        ('auth:view', 'auth_permission_template.read'),
        ('auth:manage', 'user_admin.read'),
        ('auth:manage', 'user_admin.edit'),
        ('auth:manage', 'auth_role.read'),
        ('auth:manage', 'auth_role.edit'),
        ('auth:manage', 'auth_permission_template.read'),
        ('auth:manage', 'auth_permission_template.edit'),
        ('system:admin', 'system.config_read'),
        ('system:admin', 'system.config_write'),
        ('system:admin', 'system.ops_admin')
)
INSERT INTO role_permissions (role_id, permission_id)
SELECT DISTINCT rp.role_id, granular_permission.id
FROM role_permissions rp
JOIN permissions legacy_permission
    ON legacy_permission.id = rp.permission_id
JOIN legacy_permission_mapping mapping
    ON mapping.legacy_name = legacy_permission.name
JOIN permissions granular_permission
    ON granular_permission.name = mapping.granular_name
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT admin_role.id, permission.id
FROM roles admin_role
JOIN permissions permission
    ON permission.name IN (
        'flight.read',
        'flight.update',
        'flight.timeline_edit',
        'flight.import_commit',
        'flight.report_generate',
        'business_case.create',
        'business_case.read',
        'business_case.append',
        'business_case.update',
        'business_case.status_transition',
        'business_case.delete',
        'workflow_run.start',
        'workflow_run.read',
        'workflow_run.act',
        'workflow_definition.read',
        'workflow_definition.edit',
        'workflow_definition.publish',
        'workflow_definition.deprecate',
        'automation.notify_send',
        'automation.dispatch_create',
        'automation.business_case_complete',
        'automation.business_case_fail',
        'automation.external_call',
        'automation.ai_execute',
        'dispatch_order.read',
        'dispatch_order.create',
        'dispatch_order.update',
        'dispatch_order.publish',
        'dispatch_order.cancel',
        'dispatch_catalog.read',
        'dispatch_catalog.edit',
        'shift_handover.read',
        'shift_handover.create',
        'shift_handover.submit',
        'shift_handover.ack',
        'notification.read',
        'notification.send',
        'notification.receipt_read',
        'notification.receipt_manage',
        'auth_role.read',
        'auth_role.edit',
        'auth_permission_template.read',
        'auth_permission_template.edit',
        'user_admin.read',
        'user_admin.edit',
        'system.config_read',
        'system.config_write',
        'system.ops_admin'
    )
WHERE admin_role.name = 'admin'
ON CONFLICT DO NOTHING;

INSERT INTO permission_templates (id, name, code, description, permissions, is_system, category, display_order)
VALUES
    (
        'tpl_dispatch_viewer',
        '派工查看员',
        'dispatch_viewer',
        '只能查看派工单、班组和设备信息',
        ARRAY[
            'dispatch:view',
            'dispatch_order.read',
            'dispatch_catalog.read',
            'shift_handover.read',
            'notification.read',
            'notification.receipt_read',
            'team:view',
            'equipment:view'
        ],
        TRUE,
        'dispatch',
        1
    ),
    (
        'tpl_dispatch_operator',
        '派工操作员',
        'dispatch_operator',
        '可查看和执行派工操作，但不能管理班组和设备',
        ARRAY[
            'dispatch:view',
            'dispatch:manage',
            'dispatch_order.read',
            'dispatch_order.create',
            'dispatch_order.update',
            'dispatch_order.publish',
            'dispatch_order.cancel',
            'dispatch_catalog.read',
            'shift_handover.read',
            'shift_handover.create',
            'shift_handover.submit',
            'shift_handover.ack',
            'notification.read',
            'notification.send',
            'notification.receipt_read',
            'notification.receipt_manage',
            'team:view',
            'equipment:view'
        ],
        TRUE,
        'dispatch',
        2
    ),
    (
        'tpl_dispatch_admin',
        '派工管理员',
        'dispatch_admin',
        '完全的派工系统管理权限',
        ARRAY[
            'dispatch:view',
            'dispatch:manage',
            'dispatch_order.read',
            'dispatch_order.create',
            'dispatch_order.update',
            'dispatch_order.publish',
            'dispatch_order.cancel',
            'dispatch_catalog.read',
            'dispatch_catalog.edit',
            'shift_handover.read',
            'shift_handover.create',
            'shift_handover.submit',
            'shift_handover.ack',
            'notification.read',
            'notification.send',
            'notification.receipt_read',
            'notification.receipt_manage',
            'team:view',
            'team:manage',
            'equipment:view',
            'equipment:manage',
            'schedule:view',
            'schedule:manage'
        ],
        TRUE,
        'dispatch',
        3
    ),
    (
        'tpl_flight_viewer',
        '航班查看员',
        'flight_viewer',
        '只能查看航班信息',
        ARRAY['flight:read', 'flight.read', 'business_case.read', 'workflow_run.read'],
        TRUE,
        'flight',
        1
    ),
    (
        'tpl_flight_operator',
        '航班操作员',
        'flight_operator',
        '可查看和编辑航班信息',
        ARRAY[
            'flight:read',
            'flight:manage',
            'flight.read',
            'flight.update',
            'flight.timeline_edit',
            'flight.report_generate',
            'business_case.create',
            'business_case.read',
            'business_case.append',
            'business_case.update',
            'business_case.status_transition',
            'workflow_run.start',
            'workflow_run.read',
            'workflow_run.act'
        ],
        TRUE,
        'flight',
        2
    ),
    (
        'tpl_workflow_editor',
        '流程编排维护员',
        'workflow_editor',
        '可维护并发布基础流程编排，包含通知与事项状态自动化能力',
        ARRAY[
            'workflow_definition.read',
            'workflow_definition.edit',
            'workflow_definition.publish',
            'workflow_definition.deprecate',
            'automation.notify_send',
            'automation.business_case_complete',
            'automation.business_case_fail'
        ],
        TRUE,
        'workflow',
        1
    ),
    (
        'tpl_workflow_dispatch_ops',
        '流程派工编排维护员',
        'workflow_dispatch_editor',
        '在基础流程编排权限上，额外允许自动派工能力',
        ARRAY[
            'workflow_definition.read',
            'workflow_definition.edit',
            'workflow_definition.publish',
            'workflow_definition.deprecate',
            'automation.notify_send',
            'automation.dispatch_create',
            'automation.business_case_complete',
            'automation.business_case_fail'
        ],
        TRUE,
        'workflow',
        2
    ),
    (
        'tpl_user_viewer',
        '用户查看员',
        'user_viewer',
        '只能查看用户信息',
        ARRAY['user:read', 'user_admin.read'],
        TRUE,
        'user',
        1
    ),
    (
        'tpl_user_admin',
        '用户管理员',
        'user_admin',
        '完全的用户管理权限',
        ARRAY[
            'user:read',
            'user:create',
            'user:update',
            'user:delete',
            'role:read',
            'role:create',
            'role:update',
            'role:delete',
            'user_admin.read',
            'user_admin.edit',
            'auth_role.read',
            'auth_role.edit',
            'auth_permission_template.read',
            'auth_permission_template.edit',
            'system.config_read'
        ],
        TRUE,
        'user',
        2
    )
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    code = EXCLUDED.code,
    description = EXCLUDED.description,
    permissions = EXCLUDED.permissions,
    is_system = EXCLUDED.is_system,
    category = EXCLUDED.category,
    display_order = EXCLUDED.display_order,
    is_active = TRUE,
    updated_at = CURRENT_TIMESTAMP;


