import type { WorkbenchData } from './types';
import { workspaceOpenUrl } from '@/shared/workspace-modules';

export function getDefaultWorkbenchData(): WorkbenchData {
  return {
    user_name: '值班员',
    user_role: undefined,
    shift_label: undefined,
    my_tasks: [
      {
        id: 'task-1',
        title: '监控早高峰离港航班',
        description: 'COBT < 45min 且状态异常的航班需优先保障',
        priority: 'high',
        due: '今日 09:00',
        href: workspaceOpenUrl('flight_monitor'),
        status: 'pending',
      },
      {
        id: 'task-2',
        title: '确认机位冲突航班调舱',
        description: '3架航班共享同一机位，需协调停机位分配',
        priority: 'high',
        href: workspaceOpenUrl('flight_monitor'),
        status: 'pending',
      },
      {
        id: 'task-3',
        title: '复核 AI 航班重排建议',
        description: 'AI 建议对 12 架进港航班调整 COBT，请值班经理确认',
        priority: 'medium',
        href: workspaceOpenUrl('dispatch_board'),
        status: 'pending',
      },
    ],
    operation_risks: [
      {
        id: 'risk-1',
        title: '航班保障超时',
        description: '当前有 4 架航班地面保障时间超过阈值',
        severity: 'warning',
        count: 4,
        href: workspaceOpenUrl('flight_monitor'),
      },
      {
        id: 'risk-2',
        title: '机位饱和',
        description: '本时段机位占用率超过 90%，建议启动临时停机位',
        severity: 'critical',
        count: 0,
        href: workspaceOpenUrl('resource_utilization'),
      },
      {
        id: 'risk-3',
        title: '登机口变更频繁',
        description: '最近 30 分钟内已发生 8 次登机口变更',
        severity: 'info',
        count: 8,
        href: workspaceOpenUrl('flight_monitor'),
      },
    ],
    recent_changes: [
      {
        id: 'change-1',
        title: 'MU2514 目的地变更',
        description: '备降计划取消，恢复原目的地武汉',
        timestamp: '08:42',
        actor: '调度员A',
        type: 'flight_update',
      },
      {
        id: 'change-2',
        title: '登机口 D12 关闭',
        description: 'D12 登机口因设备维护暂时关闭，已重新分配 CA1234 至 D08',
        timestamp: '08:31',
        actor: '系统',
        type: 'resource_change',
      },
      {
        id: 'change-3',
        title: '新派工单生成',
        description: '派工板新增 3 条派工任务，等待确认',
        timestamp: '08:15',
        actor: 'AI 助手',
        type: 'dispatch_created',
      },
    ],
    quick_links: [
      {
        id: 'ql-monitor',
        title: '航班监控',
        description: '实时航班动态',
        icon: 'plane',
        href: workspaceOpenUrl('flight_monitor'),
        theme: 'theme-orange',
      },
      {
        id: 'ql-dispatch',
        title: '派工调度',
        description: '甘特图派工与重排',
        icon: 'bar_chart',
        href: workspaceOpenUrl('dispatch_board'),
        theme: 'theme-blue',
        wide: true,
      },
      {
        id: 'ql-kpi',
        title: 'KPI 诊断',
        description: '性能指标分析',
        icon: 'bar_chart',
        href: workspaceOpenUrl('kpi_dashboard'),
        theme: 'theme-purple',
      },
      {
        id: 'ql-resource',
        title: '资源管理',
        description: '人员设备调度',
        icon: 'users',
        href: workspaceOpenUrl('resource_manager'),
        theme: 'theme-teal',
      },
      {
        id: 'ql-status',
        title: '系统状态',
        description: '基础设施健康',
        icon: 'settings',
        href: workspaceOpenUrl('system_status'),
        theme: 'theme-dark',
      },
      {
        id: 'ql-anomaly',
        title: '异常监控',
        description: '异常检测与处置',
        icon: 'activity',
        href: workspaceOpenUrl('anomaly_monitor'),
        theme: 'theme-red',
      },
    ],
    modules: [
      {
        id: 'dispatch',
        title: '派工调度台',
        description: '甘特图派工、智能重排与冲突治理',
        icon: 'bar_chart',
        href: workspaceOpenUrl('dispatch_board'),
        theme: 'theme-blue',
        wide: true,
      },
      {
        id: 'flowable',
        title: '流程设计器',
        description: 'BPMN 2.0 流程建模与配置管理',
        icon: 'refresh',
        href: workspaceOpenUrl('flowable_modeler'),
        theme: 'theme-green',
      },
      {
        id: 'monitor',
        title: '航班监控',
        description: '实时航班动态与异常监控',
        icon: 'plane',
        href: workspaceOpenUrl('flight_monitor'),
        theme: 'theme-orange',
      },
      {
        id: 'kpi',
        title: 'KPI 诊断',
        description: '性能指标分析与趋势诊断',
        icon: 'bar_chart',
        href: workspaceOpenUrl('kpi_dashboard'),
        theme: 'theme-purple',
      },
      {
        id: 'resources',
        title: '资源管理',
        description: '人员、设备与班组资源调度',
        icon: 'users',
        href: workspaceOpenUrl('resource_manager'),
        theme: 'theme-teal',
      },
      {
        id: 'system',
        title: '系统状态',
        description: '基础设施健康监控与日志',
        icon: 'settings',
        href: workspaceOpenUrl('system_status'),
        theme: 'theme-dark',
      },
    ],
  };
}
