//! 系统管理路由
//!
//! 对齐 Python `system_routes.py`。

use actix_multipart::Multipart;
use actix_web::{web, HttpRequest, HttpResponse};
use futures_util::{StreamExt, TryStreamExt};
use serde::Deserialize;
use serde_json::json;
use std::sync::Arc;

use crate::error::ApiError;
use crate::middleware::jwt::JwtAuth;
use crate::middleware::permissions::PermissionCheck;
use crate::sse::hub::SseHub;
use fms_application::services::flight_import_service::{FlightImportError, FlightImportService};
use fms_application::services::system_flags_service::SystemFlagsService;
use fms_application::services::system_ops_service::SystemOpsService;

fn ensure_admin(claims: &JwtAuth) -> Result<(), ApiError> {
    if claims.0.is_admin.unwrap_or(false) {
        Ok(())
    } else {
        Err(ApiError::Forbidden("管理员权限不足".into()))
    }
}

fn request_id(req: &HttpRequest) -> Option<String> {
    req.headers()
        .get("x-request-id")
        .or_else(|| req.headers().get("x-trace-id"))
        .and_then(|value| value.to_str().ok())
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(str::to_string)
}

fn actor_id(claims: &JwtAuth) -> String {
    claims
        .0
        .sub
        .as_deref()
        .or(claims.0.username.as_deref())
        .filter(|value| !value.trim().is_empty())
        .unwrap_or("system_admin")
        .to_string()
}

fn map_import_error(error: FlightImportError, preview_id: Option<&str>) -> ApiError {
    match error {
        FlightImportError::Validation(message) => ApiError::BadRequest(message),
        FlightImportError::NotFound(_) => ApiError::NotFound(match preview_id {
            Some(id) => format!("导入预览不存在: {id}"),
            None => "导入预览不存在".to_string(),
        }),
        FlightImportError::Conflict(message) => ApiError::Conflict(message),
        FlightImportError::Internal(message) => ApiError::Internal(message),
    }
}

#[derive(Deserialize)]
struct UpdateSystemFlagRequest {
    path: String,
    value: serde_json::Value,
}

#[derive(Deserialize)]
struct TestAlertRequest {
    title: Option<String>,
    message: Option<String>,
    level: Option<String>,
    channels: Option<Vec<String>>,
    recipients: Option<Vec<String>>,
}

/// GET /api/v2/system/health
async fn system_health(system_ops_service: web::Data<Arc<SystemOpsService>>) -> Result<HttpResponse, ApiError> {
    Ok(HttpResponse::Ok().json(system_ops_service.get_public_health().await?))
}

/// GET /api/v2/system/airport-context
async fn airport_context(flags_service: web::Data<Arc<SystemFlagsService>>) -> Result<HttpResponse, ApiError> {
    Ok(HttpResponse::Ok().json(flags_service.get_airport_context().await))
}

/// GET /api/v2/system/online-status/service-status
async fn online_status_service_status(
    system_ops_service: web::Data<Arc<SystemOpsService>>,
    claims: JwtAuth,
) -> Result<HttpResponse, ApiError> {
    ensure_admin(&claims)?;
    Ok(HttpResponse::Ok().json(json!({
        "success": true,
        "data": system_ops_service.get_online_status_runtime_status().await?,
    })))
}

/// POST /api/v2/system/alert/test
async fn test_alert(
    system_ops_service: web::Data<Arc<SystemOpsService>>,
    hub: web::Data<Arc<SseHub>>,
    claims: JwtAuth,
    body: Option<web::Json<TestAlertRequest>>,
) -> Result<HttpResponse, ApiError> {
    ensure_admin(&claims)?;
    let payload = body.map(|value| value.into_inner()).unwrap_or(TestAlertRequest {
        title: Some("Flight Monitor Test Alert".to_string()),
        message: Some("This is a test alert generated by system admin.".to_string()),
        level: Some("warning".to_string()),
        channels: Some(vec!["log".to_string(), "email".to_string()]),
        recipients: Some(Vec::new()),
    });
    let title = payload.title.unwrap_or_else(|| "Flight Monitor Test Alert".to_string());
    let message = payload
        .message
        .unwrap_or_else(|| "This is a test alert generated by system admin.".to_string());
    let level = payload.level.unwrap_or_else(|| "warning".to_string());
    let channels = payload
        .channels
        .unwrap_or_else(|| vec!["log".to_string(), "email".to_string()]);
    let recipients = payload.recipients.unwrap_or_default();
    let requested_by = claims.0.sub.as_deref().unwrap_or("system_admin");
    let result = system_ops_service
        .send_test_alert(&title, &message, &level, &channels, &recipients, requested_by)
        .await?;

    let _ = hub
        .broadcast_event(
            "global_status",
            Some("system_alert"),
            json!({
                "type": "manual_test_alert",
                "title": title,
                "message": message,
                "level": level,
                "channels": channels,
                "recipients": recipients,
                "requested_by": requested_by,
                "timestamp": chrono::Utc::now().to_rfc3339(),
            }),
        )
        .await;

    Ok(HttpResponse::Ok().json(json!({
        "success": true,
        "message": "Test alert sent",
        "data": result,
    })))
}

/// GET /api/v2/system/flags
async fn get_flags(
    flags_service: web::Data<Arc<SystemFlagsService>>,
    claims: JwtAuth,
) -> Result<HttpResponse, ApiError> {
    claims.ensure_permission("system:config")?;
    Ok(HttpResponse::Ok().json(json!({
        "success": true,
        "data": {
            "flags": flags_service.get_flags().await,
        },
    })))
}

/// PATCH /api/v2/system/flags
async fn update_flag(
    flags_service: web::Data<Arc<SystemFlagsService>>,
    claims: JwtAuth,
    body: web::Json<UpdateSystemFlagRequest>,
) -> Result<HttpResponse, ApiError> {
    claims.ensure_permission("system:config")?;
    let updated = flags_service.update_flag(&body.path, body.value.clone()).await?;

    Ok(HttpResponse::Ok().json(json!({
        "success": true,
        "data": {
            "path": updated.get("path").unwrap_or(&serde_json::Value::Null),
            "value": updated.get("value").unwrap_or(&serde_json::Value::Null),
            "needs_restart": false,
        },
    })))
}

/// GET /api/v2/system/flags/export
async fn export_flags(
    flags_service: web::Data<Arc<SystemFlagsService>>,
    claims: JwtAuth,
) -> Result<HttpResponse, ApiError> {
    claims.ensure_permission("system:config")?;
    Ok(HttpResponse::Ok().json(json!({
        "success": true,
        "data": flags_service.export_config().await,
    })))
}

/// POST /api/v2/system/flight-imports/preview
///
/// Upload size limit is enforced by the global `PayloadConfig` in `main.rs`
/// (default 20 MB). Route-level duplicate checks are removed to avoid
/// inconsistent limits.
async fn preview_flight_import(
    import_service: web::Data<Arc<FlightImportService>>,
    claims: JwtAuth,
    mut multipart: Multipart,
) -> Result<HttpResponse, ApiError> {
    ensure_admin(&claims)?;
    claims.ensure_permission("flight:manage")?;

    let mut file_name: Option<String> = None;
    let mut file_bytes = Vec::new();

    while let Some(mut field) = multipart
        .try_next()
        .await
        .map_err(|error| ApiError::BadRequest(format!("读取上传表单失败: {error}")))?
    {
        let field_name = field
            .content_disposition()
            .and_then(|disposition| disposition.get_name())
            .unwrap_or("")
            .to_string();
        if field_name != "file" {
            continue;
        }

        file_name = field
            .content_disposition()
            .and_then(|disposition| disposition.get_filename())
            .map(str::to_string)
            .or_else(|| Some("flight-import.csv".to_string()));

        while let Some(chunk) = field.next().await {
            let chunk = chunk.map_err(|error| ApiError::BadRequest(format!("读取上传文件失败: {error}")))?;
            file_bytes.extend_from_slice(&chunk);
        }
    }

    if file_bytes.is_empty() {
        return Err(ApiError::BadRequest("请上传导入文件".to_string()));
    }

    let preview = import_service
        .create_preview_from_bytes(file_name.as_deref().unwrap_or("flight-import.csv"), &file_bytes)
        .await
        .map_err(|error| map_import_error(error, None))?;
    Ok(HttpResponse::Ok().json(preview))
}

/// GET /api/v2/system/flight-imports/{preview_id}
async fn get_flight_import_preview(
    import_service: web::Data<Arc<FlightImportService>>,
    claims: JwtAuth,
    path: web::Path<String>,
) -> Result<HttpResponse, ApiError> {
    ensure_admin(&claims)?;
    claims.ensure_permission("flight:manage")?;
    let preview_id = path.into_inner();
    let preview = import_service
        .get_preview(&preview_id)
        .map_err(|error| map_import_error(error, Some(&preview_id)))?;
    Ok(HttpResponse::Ok().json(preview))
}

/// POST /api/v2/system/flight-imports/{preview_id}/commit
async fn commit_flight_import(
    req: HttpRequest,
    import_service: web::Data<Arc<FlightImportService>>,
    claims: JwtAuth,
    path: web::Path<String>,
) -> Result<HttpResponse, ApiError> {
    ensure_admin(&claims)?;
    claims.ensure_permission("flight:manage")?;
    let preview_id = path.into_inner();
    let result = import_service
        .commit_preview(&preview_id, &actor_id(&claims), request_id(&req))
        .await
        .map_err(|error| map_import_error(error, Some(&preview_id)))?;
    Ok(HttpResponse::Ok().json(result))
}

/// GET /api/v2/system/flight-imports/{preview_id}/result
async fn get_flight_import_result(
    import_service: web::Data<Arc<FlightImportService>>,
    claims: JwtAuth,
    path: web::Path<String>,
) -> Result<HttpResponse, ApiError> {
    ensure_admin(&claims)?;
    claims.ensure_permission("flight:manage")?;
    let preview_id = path.into_inner();
    let result = import_service.get_result(&preview_id).map_err(|error| match error {
        FlightImportError::NotFound(_) => ApiError::NotFound(format!("导入结果不存在: {preview_id}")),
        FlightImportError::Validation(message) => ApiError::BadRequest(message),
        FlightImportError::Conflict(message) => ApiError::Conflict(message),
        FlightImportError::Internal(message) => ApiError::Internal(message),
    })?;
    Ok(HttpResponse::Ok().json(result))
}

/// 注册系统路由
pub fn configure(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/api/v2/system")
            .route("/health", web::get().to(system_health))
            .route("/airport-context", web::get().to(airport_context))
            .route(
                "/online-status/service-status",
                web::get().to(online_status_service_status),
            )
            .route("/alert/test", web::post().to(test_alert))
            .route("/flight-imports/preview", web::post().to(preview_flight_import))
            .route("/flight-imports/{preview_id}", web::get().to(get_flight_import_preview))
            .route(
                "/flight-imports/{preview_id}/commit",
                web::post().to(commit_flight_import),
            )
            .route(
                "/flight-imports/{preview_id}/result",
                web::get().to(get_flight_import_result),
            )
            .route("/flags", web::get().to(get_flags))
            .route("/flags", web::patch().to(update_flag))
            .route("/flags/export", web::get().to(export_flags)),
    );
}
