// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_metadata`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Login and activate the session. On success Dart must persist
/// [`super::session::current_token_bundle`] into flutter_secure_storage.
Future<void> login({required String username, required String password}) =>
    RustLib.instance.api.crateApiAuthLogin(
      username: username,
      password: password,
    );

/// Register this device. `platform` is always `"android"`.
Future<DeviceInfo> registerDevice({required DeviceRegisterInfo info}) =>
    RustLib.instance.api.crateApiAuthRegisterDevice(info: info);

/// Device heartbeat. Uses the runtime's operator-context id as the device id
/// (same ANDROID_ID used at register).
Future<DeviceInfo> deviceHeartbeat({required DeviceHeartbeatMeta meta}) =>
    RustLib.instance.api.crateApiAuthDeviceHeartbeat(meta: meta);

/// Auth keep-alive heartbeat.
Future<void> authHeartbeat() =>
    RustLib.instance.api.crateApiAuthAuthHeartbeat();

/// Device heartbeat payload (mirror of `MobileDeviceHeartbeatRequest`).
class DeviceHeartbeatMeta {
  final String? networkStatus;
  final PlatformInt64? batteryLevel;
  final String? metadataJson;

  const DeviceHeartbeatMeta({
    this.networkStatus,
    this.batteryLevel,
    this.metadataJson,
  });

  @override
  int get hashCode =>
      networkStatus.hashCode ^ batteryLevel.hashCode ^ metadataJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceHeartbeatMeta &&
          runtimeType == other.runtimeType &&
          networkStatus == other.networkStatus &&
          batteryLevel == other.batteryLevel &&
          metadataJson == other.metadataJson;
}

/// Mirror of `mobile_core::dto::mobile::MobileDeviceResponse`.
class DeviceInfo {
  final String deviceId;
  final String userId;
  final bool isActive;
  final String lastHeartbeatAt;

  const DeviceInfo({
    required this.deviceId,
    required this.userId,
    required this.isActive,
    required this.lastHeartbeatAt,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      userId.hashCode ^
      isActive.hashCode ^
      lastHeartbeatAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceInfo &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          userId == other.userId &&
          isActive == other.isActive &&
          lastHeartbeatAt == other.lastHeartbeatAt;
}

/// Device registration payload (mirror of
/// `mobile_core::dto::mobile::MobileDeviceRegisterRequest`). `metadata` is
/// passed as a JSON string because frb has no arbitrary-JSON map type.
class DeviceRegisterInfo {
  final String deviceId;
  final String? pushChannel;
  final String? pushToken;
  final String? appVersion;
  final String? osVersion;
  final String? deviceModel;
  final String? manufacturer;
  final String? metadataJson;

  const DeviceRegisterInfo({
    required this.deviceId,
    this.pushChannel,
    this.pushToken,
    this.appVersion,
    this.osVersion,
    this.deviceModel,
    this.manufacturer,
    this.metadataJson,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      pushChannel.hashCode ^
      pushToken.hashCode ^
      appVersion.hashCode ^
      osVersion.hashCode ^
      deviceModel.hashCode ^
      manufacturer.hashCode ^
      metadataJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceRegisterInfo &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          pushChannel == other.pushChannel &&
          pushToken == other.pushToken &&
          appVersion == other.appVersion &&
          osVersion == other.osVersion &&
          deviceModel == other.deviceModel &&
          manufacturer == other.manufacturer &&
          metadataJson == other.metadataJson;
}
