// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `from`

Future<List<BusinessCase>> businessCases({
  String? status,
  String? caseType,
  String? flightId,
}) => RustLib.instance.api.crateApiBusinessCaseBusinessCases(
  status: status,
  caseType: caseType,
  flightId: flightId,
);

Future<BusinessCase> businessCaseDetail({required String id}) =>
    RustLib.instance.api.crateApiBusinessCaseBusinessCaseDetail(id: id);

Future<BusinessCase> createBusinessCase({
  required String caseType,
  required String flightId,
  required String description,
  required String visibilityScope,
}) => RustLib.instance.api.crateApiBusinessCaseCreateBusinessCase(
  caseType: caseType,
  flightId: flightId,
  description: description,
  visibilityScope: visibilityScope,
);

Future<BusinessCase> appendBusinessCase({
  required String caseId,
  required String content,
}) => RustLib.instance.api.crateApiBusinessCaseAppendBusinessCase(
  caseId: caseId,
  content: content,
);

Future<void> ackAppend({required String caseId, required String appendId}) =>
    RustLib.instance.api.crateApiBusinessCaseAckAppend(
      caseId: caseId,
      appendId: appendId,
    );

Future<List<BusinessCaseType>> businessCaseTypes({required bool activeOnly}) =>
    RustLib.instance.api.crateApiBusinessCaseBusinessCaseTypes(
      activeOnly: activeOnly,
    );

Future<WorkflowStartResult> startCaseWorkflow({
  required String templateCode,
  required String flightId,
  required String description,
}) => RustLib.instance.api.crateApiBusinessCaseStartCaseWorkflow(
  templateCode: templateCode,
  flightId: flightId,
  description: description,
);

Future<WorkflowDetail> caseWorkflow({required String caseId}) =>
    RustLib.instance.api.crateApiBusinessCaseCaseWorkflow(caseId: caseId);

class BusinessCase {
  final String caseId;
  final String caseType;
  final String? caseTypeName;
  final String flightId;
  final String flightNo;
  final String createdAt;
  final String createdBy;
  final String description;
  final String status;
  final String? stand;
  final String? gate;
  final String visibilityScope;
  final String? departmentNameSnapshot;
  final String? finishedAt;
  final PlatformInt64 appendCount;
  final BusinessCaseAppend? latestAppend;
  final List<BusinessCaseAppend> appendEntries;

  const BusinessCase({
    required this.caseId,
    required this.caseType,
    this.caseTypeName,
    required this.flightId,
    required this.flightNo,
    required this.createdAt,
    required this.createdBy,
    required this.description,
    required this.status,
    this.stand,
    this.gate,
    required this.visibilityScope,
    this.departmentNameSnapshot,
    this.finishedAt,
    required this.appendCount,
    this.latestAppend,
    required this.appendEntries,
  });

  @override
  int get hashCode =>
      caseId.hashCode ^
      caseType.hashCode ^
      caseTypeName.hashCode ^
      flightId.hashCode ^
      flightNo.hashCode ^
      createdAt.hashCode ^
      createdBy.hashCode ^
      description.hashCode ^
      status.hashCode ^
      stand.hashCode ^
      gate.hashCode ^
      visibilityScope.hashCode ^
      departmentNameSnapshot.hashCode ^
      finishedAt.hashCode ^
      appendCount.hashCode ^
      latestAppend.hashCode ^
      appendEntries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BusinessCase &&
          runtimeType == other.runtimeType &&
          caseId == other.caseId &&
          caseType == other.caseType &&
          caseTypeName == other.caseTypeName &&
          flightId == other.flightId &&
          flightNo == other.flightNo &&
          createdAt == other.createdAt &&
          createdBy == other.createdBy &&
          description == other.description &&
          status == other.status &&
          stand == other.stand &&
          gate == other.gate &&
          visibilityScope == other.visibilityScope &&
          departmentNameSnapshot == other.departmentNameSnapshot &&
          finishedAt == other.finishedAt &&
          appendCount == other.appendCount &&
          latestAppend == other.latestAppend &&
          appendEntries == other.appendEntries;
}

class BusinessCaseAppend {
  final String appendId;
  final String caseId;
  final String content;
  final String submittedBy;
  final String? submittedOperatorName;
  final String appendedAt;

  const BusinessCaseAppend({
    required this.appendId,
    required this.caseId,
    required this.content,
    required this.submittedBy,
    this.submittedOperatorName,
    required this.appendedAt,
  });

  @override
  int get hashCode =>
      appendId.hashCode ^
      caseId.hashCode ^
      content.hashCode ^
      submittedBy.hashCode ^
      submittedOperatorName.hashCode ^
      appendedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BusinessCaseAppend &&
          runtimeType == other.runtimeType &&
          appendId == other.appendId &&
          caseId == other.caseId &&
          content == other.content &&
          submittedBy == other.submittedBy &&
          submittedOperatorName == other.submittedOperatorName &&
          appendedAt == other.appendedAt;
}

class BusinessCaseType {
  final String id;
  final String code;
  final String name;
  final String? description;
  final bool isActive;
  final String visibilityScope;

  const BusinessCaseType({
    required this.id,
    required this.code,
    required this.name,
    this.description,
    required this.isActive,
    required this.visibilityScope,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      code.hashCode ^
      name.hashCode ^
      description.hashCode ^
      isActive.hashCode ^
      visibilityScope.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BusinessCaseType &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          code == other.code &&
          name == other.name &&
          description == other.description &&
          isActive == other.isActive &&
          visibilityScope == other.visibilityScope;
}

class WorkflowDetail {
  final WorkflowRun? run;
  final BusinessCase? businessCase;

  const WorkflowDetail({this.run, this.businessCase});

  @override
  int get hashCode => run.hashCode ^ businessCase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkflowDetail &&
          runtimeType == other.runtimeType &&
          run == other.run &&
          businessCase == other.businessCase;
}

class WorkflowRun {
  final String runId;
  final String templateCode;
  final String caseId;
  final String flightId;
  final String processInstanceId;
  final String status;
  final String? outcome;
  final String startedBy;
  final String createdAt;
  final String updatedAt;

  const WorkflowRun({
    required this.runId,
    required this.templateCode,
    required this.caseId,
    required this.flightId,
    required this.processInstanceId,
    required this.status,
    this.outcome,
    required this.startedBy,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      runId.hashCode ^
      templateCode.hashCode ^
      caseId.hashCode ^
      flightId.hashCode ^
      processInstanceId.hashCode ^
      status.hashCode ^
      outcome.hashCode ^
      startedBy.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkflowRun &&
          runtimeType == other.runtimeType &&
          runId == other.runId &&
          templateCode == other.templateCode &&
          caseId == other.caseId &&
          flightId == other.flightId &&
          processInstanceId == other.processInstanceId &&
          status == other.status &&
          outcome == other.outcome &&
          startedBy == other.startedBy &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class WorkflowStartResult {
  final String? processInstanceId;
  final bool workflowTriggered;
  final String? receiptGroupId;
  final BusinessCase? businessCase;
  final WorkflowRun? run;

  const WorkflowStartResult({
    this.processInstanceId,
    required this.workflowTriggered,
    this.receiptGroupId,
    this.businessCase,
    this.run,
  });

  @override
  int get hashCode =>
      processInstanceId.hashCode ^
      workflowTriggered.hashCode ^
      receiptGroupId.hashCode ^
      businessCase.hashCode ^
      run.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkflowStartResult &&
          runtimeType == other.runtimeType &&
          processInstanceId == other.processInstanceId &&
          workflowTriggered == other.workflowTriggered &&
          receiptGroupId == other.receiptGroupId &&
          businessCase == other.businessCase &&
          run == other.run;
}
