// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// `GET /api/v2/dispatch/collaboration/groups`.
Future<ChatGroupList> chatGroups({
  required String status,
  required PlatformInt64 limit,
  required PlatformInt64 offset,
}) => RustLib.instance.api.crateApiChatChatGroups(
  status: status,
  limit: limit,
  offset: offset,
);

/// `GET .../groups/{group_id}/messages`.
Future<ChatMessageList> chatMessages({
  required String groupId,
  required PlatformInt64 limit,
  PlatformInt64? beforeSeq,
}) => RustLib.instance.api.crateApiChatChatMessages(
  groupId: groupId,
  limit: limit,
  beforeSeq: beforeSeq,
);

/// `POST .../groups/{group_id}/messages`.
Future<ChatMessage> sendChatMessage({
  required String groupId,
  required String content,
  required bool atAll,
  required List<String> mentionUserIds,
}) => RustLib.instance.api.crateApiChatSendChatMessage(
  groupId: groupId,
  content: content,
  atAll: atAll,
  mentionUserIds: mentionUserIds,
);

/// `GET .../groups/{group_id}/members`.
Future<ChatMemberList> chatGroupMembers({required String groupId}) =>
    RustLib.instance.api.crateApiChatChatGroupMembers(groupId: groupId);

/// `POST .../groups/{group_id}/read`.
Future<ChatReadResult> markChatRead({
  required String groupId,
  PlatformInt64? readSeq,
}) => RustLib.instance.api.crateApiChatMarkChatRead(
  groupId: groupId,
  readSeq: readSeq,
);

/// Mirror of `ChatGroupSummary`.
class ChatGroup {
  final String groupId;
  final String channelType;
  final String flightId;
  final String groupName;
  final String status;
  final bool readOnly;
  final PlatformInt64 memberCount;
  final PlatformInt64 unreadCount;
  final PlatformInt64? lastMessageSeq;
  final String? lastMessagePreview;
  final String? lastMessageAt;

  const ChatGroup({
    required this.groupId,
    required this.channelType,
    required this.flightId,
    required this.groupName,
    required this.status,
    required this.readOnly,
    required this.memberCount,
    required this.unreadCount,
    this.lastMessageSeq,
    this.lastMessagePreview,
    this.lastMessageAt,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^
      channelType.hashCode ^
      flightId.hashCode ^
      groupName.hashCode ^
      status.hashCode ^
      readOnly.hashCode ^
      memberCount.hashCode ^
      unreadCount.hashCode ^
      lastMessageSeq.hashCode ^
      lastMessagePreview.hashCode ^
      lastMessageAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatGroup &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          channelType == other.channelType &&
          flightId == other.flightId &&
          groupName == other.groupName &&
          status == other.status &&
          readOnly == other.readOnly &&
          memberCount == other.memberCount &&
          unreadCount == other.unreadCount &&
          lastMessageSeq == other.lastMessageSeq &&
          lastMessagePreview == other.lastMessagePreview &&
          lastMessageAt == other.lastMessageAt;
}

/// Mirror of `ChatGroupListResponse`.
class ChatGroupList {
  final List<ChatGroup> items;
  final PlatformInt64 total;
  final PlatformInt64 limit;
  final PlatformInt64 offset;
  final PlatformInt64 unreadTotal;

  const ChatGroupList({
    required this.items,
    required this.total,
    required this.limit,
    required this.offset,
    required this.unreadTotal,
  });

  @override
  int get hashCode =>
      items.hashCode ^
      total.hashCode ^
      limit.hashCode ^
      offset.hashCode ^
      unreadTotal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatGroupList &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          total == other.total &&
          limit == other.limit &&
          offset == other.offset &&
          unreadTotal == other.unreadTotal;
}

/// Mirror of `ChatMember`.
class ChatMember {
  final String userId;
  final String username;
  final bool isAssignee;
  final bool isDispatcher;
  final bool isActive;

  const ChatMember({
    required this.userId,
    required this.username,
    required this.isAssignee,
    required this.isDispatcher,
    required this.isActive,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      username.hashCode ^
      isAssignee.hashCode ^
      isDispatcher.hashCode ^
      isActive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMember &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          username == other.username &&
          isAssignee == other.isAssignee &&
          isDispatcher == other.isDispatcher &&
          isActive == other.isActive;
}

/// Mirror of `ChatMemberList`.
class ChatMemberList {
  final List<ChatMember> items;

  const ChatMemberList({required this.items});

  @override
  int get hashCode => items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMemberList &&
          runtimeType == other.runtimeType &&
          items == other.items;
}

/// Mirror of `ChatMessage`.
class ChatMessage {
  final String messageId;
  final PlatformInt64 seqNo;
  final String groupId;
  final String? senderUserId;
  final String? senderUsername;
  final String messageType;
  final String content;
  final bool isAtAll;
  final List<String> mentionUserIds;
  final String sentAt;

  const ChatMessage({
    required this.messageId,
    required this.seqNo,
    required this.groupId,
    this.senderUserId,
    this.senderUsername,
    required this.messageType,
    required this.content,
    required this.isAtAll,
    required this.mentionUserIds,
    required this.sentAt,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      seqNo.hashCode ^
      groupId.hashCode ^
      senderUserId.hashCode ^
      senderUsername.hashCode ^
      messageType.hashCode ^
      content.hashCode ^
      isAtAll.hashCode ^
      mentionUserIds.hashCode ^
      sentAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          seqNo == other.seqNo &&
          groupId == other.groupId &&
          senderUserId == other.senderUserId &&
          senderUsername == other.senderUsername &&
          messageType == other.messageType &&
          content == other.content &&
          isAtAll == other.isAtAll &&
          mentionUserIds == other.mentionUserIds &&
          sentAt == other.sentAt;
}

/// Mirror of `ChatMessageListResponse`.
class ChatMessageList {
  final List<ChatMessage> items;
  final PlatformInt64 total;
  final PlatformInt64 limit;
  final PlatformInt64? beforeSeq;
  final bool hasMore;
  final PlatformInt64? nextBeforeSeq;

  const ChatMessageList({
    required this.items,
    required this.total,
    required this.limit,
    this.beforeSeq,
    required this.hasMore,
    this.nextBeforeSeq,
  });

  @override
  int get hashCode =>
      items.hashCode ^
      total.hashCode ^
      limit.hashCode ^
      beforeSeq.hashCode ^
      hasMore.hashCode ^
      nextBeforeSeq.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageList &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          total == other.total &&
          limit == other.limit &&
          beforeSeq == other.beforeSeq &&
          hasMore == other.hasMore &&
          nextBeforeSeq == other.nextBeforeSeq;
}

/// Mirror of `ChatReadResult`.
class ChatReadResult {
  final String? groupId;
  final PlatformInt64 unreadCount;
  final PlatformInt64 unreadTotal;
  final PlatformInt64? readSeq;
  final String? readAt;

  const ChatReadResult({
    this.groupId,
    required this.unreadCount,
    required this.unreadTotal,
    this.readSeq,
    this.readAt,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^
      unreadCount.hashCode ^
      unreadTotal.hashCode ^
      readSeq.hashCode ^
      readAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatReadResult &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          unreadCount == other.unreadCount &&
          unreadTotal == other.unreadTotal &&
          readSeq == other.readSeq &&
          readAt == other.readAt;
}
