// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `guess_content_type`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// `GET /api/v2/mobile/workbench`.
Future<Workbench> workbench({
  required PlatformInt64 pendingSyncCount,
  required PlatformInt64 maxOrders,
}) => RustLib.instance.api.crateApiDispatchWorkbench(
  pendingSyncCount: pendingSyncCount,
  maxOrders: maxOrders,
);

/// `GET /api/v2/dispatch-orders/my/assigned` (optional status filter).
Future<List<DispatchOrder>> myAssignedOrders({String? status}) =>
    RustLib.instance.api.crateApiDispatchMyAssignedOrders(status: status);

/// Send one dispatch action, queueing offline on network-class errors only
///. `action_json` is `{"action_type": "...", "payload": {...}}` where
/// `action_type` is one of `accept|checkin|checkout|start|complete|
/// eta_report|report_issue` and `payload` the action-specific request body.
Future<DispatchActionResult> dispatchAction({
  required String orderId,
  required String actionJson,
}) => RustLib.instance.api.crateApiDispatchDispatchAction(
  orderId: orderId,
  actionJson: actionJson,
);

/// Replay the offline queue through
/// `POST /api/v2/dispatch-orders/mobile/sync/actions`.
Future<SyncSummary> syncOfflineActions() =>
    RustLib.instance.api.crateApiDispatchSyncOfflineActions();

/// `GET /api/v2/dispatch-orders/{order_id}/safety-checklist`.
Future<SafetyChecklist> safetyChecklist({required String orderId}) =>
    RustLib.instance.api.crateApiDispatchSafetyChecklist(orderId: orderId);

/// `POST .../safety-checklist/items/{item_code}`. `result` is the plain
/// checklist verdict string (`pass` / `fail` / `na`), not JSON.
Future<ChecklistRecord> submitChecklistItem({
  required String orderId,
  required String itemCode,
  required String result,
}) => RustLib.instance.api.crateApiDispatchSubmitChecklistItem(
  orderId: orderId,
  itemCode: itemCode,
  result: result,
);

/// Multipart upload `POST /api/v2/mobile/uploads`. Reads the file at `path`
/// and guesses the content type from its extension.
Future<UploadAsset> uploadAttachment({
  required String path,
  required String category,
}) => RustLib.instance.api.crateApiDispatchUploadAttachment(
  path: path,
  category: category,
);

/// Mirror of `DispatchSafetyChecklistItemStatus`.
class ChecklistItem {
  final String itemCode;
  final String title;
  final bool required_;
  final bool allowNa;
  final PlatformInt64 order;
  final String? result;
  final String? checkedBy;
  final String? checkedByUsername;
  final String? checkedAt;
  final String? note;
  final String status;

  const ChecklistItem({
    required this.itemCode,
    required this.title,
    required this.required_,
    required this.allowNa,
    required this.order,
    this.result,
    this.checkedBy,
    this.checkedByUsername,
    this.checkedAt,
    this.note,
    required this.status,
  });

  @override
  int get hashCode =>
      itemCode.hashCode ^
      title.hashCode ^
      required_.hashCode ^
      allowNa.hashCode ^
      order.hashCode ^
      result.hashCode ^
      checkedBy.hashCode ^
      checkedByUsername.hashCode ^
      checkedAt.hashCode ^
      note.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChecklistItem &&
          runtimeType == other.runtimeType &&
          itemCode == other.itemCode &&
          title == other.title &&
          required_ == other.required_ &&
          allowNa == other.allowNa &&
          order == other.order &&
          result == other.result &&
          checkedBy == other.checkedBy &&
          checkedByUsername == other.checkedByUsername &&
          checkedAt == other.checkedAt &&
          note == other.note &&
          status == other.status;
}

/// Mirror of `DispatchSafetyChecklistRecord`.
class ChecklistRecord {
  final String recordId;
  final String dispatchOrderId;
  final String itemCode;
  final String result;
  final String? checkedBy;
  final String? checkedByUsername;
  final String checkedAt;
  final String? note;
  final String? templateVersion;
  final String createdAt;
  final String updatedAt;

  const ChecklistRecord({
    required this.recordId,
    required this.dispatchOrderId,
    required this.itemCode,
    required this.result,
    this.checkedBy,
    this.checkedByUsername,
    required this.checkedAt,
    this.note,
    this.templateVersion,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      recordId.hashCode ^
      dispatchOrderId.hashCode ^
      itemCode.hashCode ^
      result.hashCode ^
      checkedBy.hashCode ^
      checkedByUsername.hashCode ^
      checkedAt.hashCode ^
      note.hashCode ^
      templateVersion.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChecklistRecord &&
          runtimeType == other.runtimeType &&
          recordId == other.recordId &&
          dispatchOrderId == other.dispatchOrderId &&
          itemCode == other.itemCode &&
          result == other.result &&
          checkedBy == other.checkedBy &&
          checkedByUsername == other.checkedByUsername &&
          checkedAt == other.checkedAt &&
          note == other.note &&
          templateVersion == other.templateVersion &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// Outcome of [`dispatch_action`] (mirror of
/// `mobile_core::api::dispatch::DispatchActionOutcome`).
enum DispatchActionResult { sent, queued }

/// Mirror of `DispatchOrderItem`. The receipt summary is an arbitrary JSON
/// object server-side, so it crosses as a raw JSON string.
class DispatchOrder {
  final String id;
  final String flightId;
  final String? stepCode;
  final String status;
  final String? terminal;
  final String? standId;
  final String? gate;
  final String? estimatedCompletionTime;
  final String originType;
  final String originLabel;
  final String notificationReceiptSummaryJson;

  const DispatchOrder({
    required this.id,
    required this.flightId,
    this.stepCode,
    required this.status,
    this.terminal,
    this.standId,
    this.gate,
    this.estimatedCompletionTime,
    required this.originType,
    required this.originLabel,
    required this.notificationReceiptSummaryJson,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      flightId.hashCode ^
      stepCode.hashCode ^
      status.hashCode ^
      terminal.hashCode ^
      standId.hashCode ^
      gate.hashCode ^
      estimatedCompletionTime.hashCode ^
      originType.hashCode ^
      originLabel.hashCode ^
      notificationReceiptSummaryJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DispatchOrder &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          flightId == other.flightId &&
          stepCode == other.stepCode &&
          status == other.status &&
          terminal == other.terminal &&
          standId == other.standId &&
          gate == other.gate &&
          estimatedCompletionTime == other.estimatedCompletionTime &&
          originType == other.originType &&
          originLabel == other.originLabel &&
          notificationReceiptSummaryJson ==
              other.notificationReceiptSummaryJson;
}

/// Mirror of `DispatchSafetyChecklistStatus`.
class SafetyChecklist {
  final String dispatchOrderId;
  final String? stepCode;
  final String? templateId;
  final String? templateVersion;
  final bool enforced;
  final bool ready;
  final PlatformInt64 requiredTotal;
  final PlatformInt64 completedRequired;
  final List<String> pendingRequiredItems;
  final List<String> failedRequiredItems;
  final List<ChecklistItem> items;

  const SafetyChecklist({
    required this.dispatchOrderId,
    this.stepCode,
    this.templateId,
    this.templateVersion,
    required this.enforced,
    required this.ready,
    required this.requiredTotal,
    required this.completedRequired,
    required this.pendingRequiredItems,
    required this.failedRequiredItems,
    required this.items,
  });

  @override
  int get hashCode =>
      dispatchOrderId.hashCode ^
      stepCode.hashCode ^
      templateId.hashCode ^
      templateVersion.hashCode ^
      enforced.hashCode ^
      ready.hashCode ^
      requiredTotal.hashCode ^
      completedRequired.hashCode ^
      pendingRequiredItems.hashCode ^
      failedRequiredItems.hashCode ^
      items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SafetyChecklist &&
          runtimeType == other.runtimeType &&
          dispatchOrderId == other.dispatchOrderId &&
          stepCode == other.stepCode &&
          templateId == other.templateId &&
          templateVersion == other.templateVersion &&
          enforced == other.enforced &&
          ready == other.ready &&
          requiredTotal == other.requiredTotal &&
          completedRequired == other.completedRequired &&
          pendingRequiredItems == other.pendingRequiredItems &&
          failedRequiredItems == other.failedRequiredItems &&
          items == other.items;
}

/// Mirror of `mobile_core::offline::SyncSummary`.
class SyncSummary {
  final PlatformInt64 total;
  final PlatformInt64 applied;
  final PlatformInt64 duplicates;
  final PlatformInt64 failed;
  final PlatformInt64 remaining;

  const SyncSummary({
    required this.total,
    required this.applied,
    required this.duplicates,
    required this.failed,
    required this.remaining,
  });

  @override
  int get hashCode =>
      total.hashCode ^
      applied.hashCode ^
      duplicates.hashCode ^
      failed.hashCode ^
      remaining.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncSummary &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          applied == other.applied &&
          duplicates == other.duplicates &&
          failed == other.failed &&
          remaining == other.remaining;
}

/// Mirror of `MobileUploadAsset` (`metadata` crosses as raw JSON string).
class UploadAsset {
  final String uploadId;
  final String originalFilename;
  final String? contentType;
  final PlatformInt64 fileSize;
  final String? checksumSha256;
  final String createdAt;
  final String attachmentUrl;
  final String metadataJson;

  const UploadAsset({
    required this.uploadId,
    required this.originalFilename,
    this.contentType,
    required this.fileSize,
    this.checksumSha256,
    required this.createdAt,
    required this.attachmentUrl,
    required this.metadataJson,
  });

  @override
  int get hashCode =>
      uploadId.hashCode ^
      originalFilename.hashCode ^
      contentType.hashCode ^
      fileSize.hashCode ^
      checksumSha256.hashCode ^
      createdAt.hashCode ^
      attachmentUrl.hashCode ^
      metadataJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UploadAsset &&
          runtimeType == other.runtimeType &&
          uploadId == other.uploadId &&
          originalFilename == other.originalFilename &&
          contentType == other.contentType &&
          fileSize == other.fileSize &&
          checksumSha256 == other.checksumSha256 &&
          createdAt == other.createdAt &&
          attachmentUrl == other.attachmentUrl &&
          metadataJson == other.metadataJson;
}

/// Mirror of `MobileWorkbenchResponse`. `channel_recommendation` is a plain
/// `Map<String, bool>` on the Dart side.
class Workbench {
  final String userId;
  final String generatedAt;
  final List<WorkbenchOrderItem> myOrders;
  final WorkbenchCounts orderCounts;
  final PlatformInt64 notificationUnreadCount;
  final PlatformInt64 chatUnreadTotal;
  final PlatformInt64 pendingShiftHandoverCount;
  final PlatformInt64 pendingSyncActionCount;
  final Map<String, bool> channelRecommendation;

  const Workbench({
    required this.userId,
    required this.generatedAt,
    required this.myOrders,
    required this.orderCounts,
    required this.notificationUnreadCount,
    required this.chatUnreadTotal,
    required this.pendingShiftHandoverCount,
    required this.pendingSyncActionCount,
    required this.channelRecommendation,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      generatedAt.hashCode ^
      myOrders.hashCode ^
      orderCounts.hashCode ^
      notificationUnreadCount.hashCode ^
      chatUnreadTotal.hashCode ^
      pendingShiftHandoverCount.hashCode ^
      pendingSyncActionCount.hashCode ^
      channelRecommendation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Workbench &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          generatedAt == other.generatedAt &&
          myOrders == other.myOrders &&
          orderCounts == other.orderCounts &&
          notificationUnreadCount == other.notificationUnreadCount &&
          chatUnreadTotal == other.chatUnreadTotal &&
          pendingShiftHandoverCount == other.pendingShiftHandoverCount &&
          pendingSyncActionCount == other.pendingSyncActionCount &&
          channelRecommendation == other.channelRecommendation;
}

/// Mirror of `MobileWorkbenchCounts`.
class WorkbenchCounts {
  final PlatformInt64 pending;
  final PlatformInt64 assigned;
  final PlatformInt64 inProgress;
  final PlatformInt64 completed;
  final PlatformInt64 cancelled;
  final PlatformInt64 total;

  const WorkbenchCounts({
    required this.pending,
    required this.assigned,
    required this.inProgress,
    required this.completed,
    required this.cancelled,
    required this.total,
  });

  @override
  int get hashCode =>
      pending.hashCode ^
      assigned.hashCode ^
      inProgress.hashCode ^
      completed.hashCode ^
      cancelled.hashCode ^
      total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkbenchCounts &&
          runtimeType == other.runtimeType &&
          pending == other.pending &&
          assigned == other.assigned &&
          inProgress == other.inProgress &&
          completed == other.completed &&
          cancelled == other.cancelled &&
          total == other.total;
}

/// Mirror of `MobileWorkbenchOrderItem`.
class WorkbenchOrderItem {
  final String orderId;
  final String flightId;
  final String? stepCode;
  final String status;
  final String? terminal;
  final String? standId;
  final String? gate;
  final String? plannedStartTime;
  final String? plannedEndTime;
  final String? actualStartTime;
  final String? assignmentDeadline;
  final bool supervisorNotified;

  const WorkbenchOrderItem({
    required this.orderId,
    required this.flightId,
    this.stepCode,
    required this.status,
    this.terminal,
    this.standId,
    this.gate,
    this.plannedStartTime,
    this.plannedEndTime,
    this.actualStartTime,
    this.assignmentDeadline,
    required this.supervisorNotified,
  });

  @override
  int get hashCode =>
      orderId.hashCode ^
      flightId.hashCode ^
      stepCode.hashCode ^
      status.hashCode ^
      terminal.hashCode ^
      standId.hashCode ^
      gate.hashCode ^
      plannedStartTime.hashCode ^
      plannedEndTime.hashCode ^
      actualStartTime.hashCode ^
      assignmentDeadline.hashCode ^
      supervisorNotified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkbenchOrderItem &&
          runtimeType == other.runtimeType &&
          orderId == other.orderId &&
          flightId == other.flightId &&
          stepCode == other.stepCode &&
          status == other.status &&
          terminal == other.terminal &&
          standId == other.standId &&
          gate == other.gate &&
          plannedStartTime == other.plannedStartTime &&
          plannedEndTime == other.plannedEndTime &&
          actualStartTime == other.actualStartTime &&
          assignmentDeadline == other.assignmentDeadline &&
          supervisorNotified == other.supervisorNotified;
}
