// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

/// `GET /api/v2/shift-handovers`.
Future<List<Handover>> shiftHandovers({
  String? status,
  required PlatformInt64 limit,
  required PlatformInt64 offset,
}) => RustLib.instance.api.crateApiHandoverShiftHandovers(
  status: status,
  limit: limit,
  offset: offset,
);

/// `GET /api/v2/shift-handovers/{id}`.
Future<Handover> shiftHandoverDetail({required String id}) =>
    RustLib.instance.api.crateApiHandoverShiftHandoverDetail(id: id);

/// `POST .../items/{item_id}/ack`.
Future<HandoverItem> ackHandoverItem({
  required String handoverId,
  required String itemId,
  required bool acknowledged,
}) => RustLib.instance.api.crateApiHandoverAckHandoverItem(
  handoverId: handoverId,
  itemId: itemId,
  acknowledged: acknowledged,
);

/// `POST .../{id}/ack` — whole-handover acknowledge.
Future<Handover> ackHandover({required String handoverId}) =>
    RustLib.instance.api.crateApiHandoverAckHandover(handoverId: handoverId);

/// Mirror of `ShiftHandover`.
class Handover {
  final String handoverId;
  final String shiftDate;
  final String shiftCode;
  final String fromUserId;
  final String toUserId;
  final String? fromOperatorName;
  final String? fromOperatorJobTitle;
  final String? fromOperatorLabel;
  final String? toOperatorName;
  final String? toOperatorJobTitle;
  final String? toOperatorLabel;
  final String status;
  final String? summary;
  final String riskLevel;
  final String? signedAt;
  final String? submittedAt;
  final String createdAt;
  final String updatedAt;
  final List<HandoverItem> items;

  const Handover({
    required this.handoverId,
    required this.shiftDate,
    required this.shiftCode,
    required this.fromUserId,
    required this.toUserId,
    this.fromOperatorName,
    this.fromOperatorJobTitle,
    this.fromOperatorLabel,
    this.toOperatorName,
    this.toOperatorJobTitle,
    this.toOperatorLabel,
    required this.status,
    this.summary,
    required this.riskLevel,
    this.signedAt,
    this.submittedAt,
    required this.createdAt,
    required this.updatedAt,
    required this.items,
  });

  @override
  int get hashCode =>
      handoverId.hashCode ^
      shiftDate.hashCode ^
      shiftCode.hashCode ^
      fromUserId.hashCode ^
      toUserId.hashCode ^
      fromOperatorName.hashCode ^
      fromOperatorJobTitle.hashCode ^
      fromOperatorLabel.hashCode ^
      toOperatorName.hashCode ^
      toOperatorJobTitle.hashCode ^
      toOperatorLabel.hashCode ^
      status.hashCode ^
      summary.hashCode ^
      riskLevel.hashCode ^
      signedAt.hashCode ^
      submittedAt.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Handover &&
          runtimeType == other.runtimeType &&
          handoverId == other.handoverId &&
          shiftDate == other.shiftDate &&
          shiftCode == other.shiftCode &&
          fromUserId == other.fromUserId &&
          toUserId == other.toUserId &&
          fromOperatorName == other.fromOperatorName &&
          fromOperatorJobTitle == other.fromOperatorJobTitle &&
          fromOperatorLabel == other.fromOperatorLabel &&
          toOperatorName == other.toOperatorName &&
          toOperatorJobTitle == other.toOperatorJobTitle &&
          toOperatorLabel == other.toOperatorLabel &&
          status == other.status &&
          summary == other.summary &&
          riskLevel == other.riskLevel &&
          signedAt == other.signedAt &&
          submittedAt == other.submittedAt &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          items == other.items;
}

/// Mirror of `ShiftHandoverItem`.
class HandoverItem {
  final String itemId;
  final String handoverId;
  final String itemType;
  final String title;
  final String? detail;
  final String? ownerUserId;
  final String? dueAt;
  final bool isMandatory;
  final bool acknowledged;
  final String? acknowledgedAt;
  final String? acknowledgedBy;
  final String createdAt;
  final String updatedAt;

  const HandoverItem({
    required this.itemId,
    required this.handoverId,
    required this.itemType,
    required this.title,
    this.detail,
    this.ownerUserId,
    this.dueAt,
    required this.isMandatory,
    required this.acknowledged,
    this.acknowledgedAt,
    this.acknowledgedBy,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      itemId.hashCode ^
      handoverId.hashCode ^
      itemType.hashCode ^
      title.hashCode ^
      detail.hashCode ^
      ownerUserId.hashCode ^
      dueAt.hashCode ^
      isMandatory.hashCode ^
      acknowledged.hashCode ^
      acknowledgedAt.hashCode ^
      acknowledgedBy.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HandoverItem &&
          runtimeType == other.runtimeType &&
          itemId == other.itemId &&
          handoverId == other.handoverId &&
          itemType == other.itemType &&
          title == other.title &&
          detail == other.detail &&
          ownerUserId == other.ownerUserId &&
          dueAt == other.dueAt &&
          isMandatory == other.isMandatory &&
          acknowledged == other.acknowledged &&
          acknowledgedAt == other.acknowledgedAt &&
          acknowledgedBy == other.acknowledgedBy &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
