// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`

/// `GET /api/v2/notifications`.
Future<NotificationList> notifications({
  required PlatformInt64 limit,
  required PlatformInt64 offset,
  required bool onlyUnread,
}) => RustLib.instance.api.crateApiNotificationNotifications(
  limit: limit,
  offset: offset,
  onlyUnread: onlyUnread,
);

/// `GET /api/v2/notifications/unread-count`.
Future<PlatformInt64> unreadCount() =>
    RustLib.instance.api.crateApiNotificationUnreadCount();

/// `POST /api/v2/notifications/{id}/read`.
Future<void> notificationRead({required String id}) =>
    RustLib.instance.api.crateApiNotificationNotificationRead(id: id);

/// `POST /api/v2/notifications/read-all`.
Future<void> notificationReadAll() =>
    RustLib.instance.api.crateApiNotificationNotificationReadAll();

/// `POST /api/v2/notifications/{id}/ack`. `action` is `ack` or `reject`.
Future<NotificationReceipt> notificationAck({
  required String id,
  required String action,
  String? note,
}) => RustLib.instance.api.crateApiNotificationNotificationAck(
  id: id,
  action: action,
  note: note,
);

/// `GET /api/v2/notifications/receipt-groups/{receipt_group_id}`.
Future<ReceiptGroup> receiptGroup({required String receiptGroupId}) => RustLib
    .instance
    .api
    .crateApiNotificationReceiptGroup(receiptGroupId: receiptGroupId);

/// Mirror of `NotificationItem`.
class Notification {
  final String notificationId;
  final String userId;
  final String title;
  final String body;
  final String category;
  final String severity;
  final bool isRead;
  final String readStatus;
  final String deliveryStatus;
  final String? deliveredAt;
  final String originType;
  final String originLabel;
  final bool receiptRequired;
  final String? receiptGroupId;
  final String ackStatus;
  final String? ackAt;
  final String? ackNote;
  final String? relatedEntityType;
  final String? relatedEntityId;
  final String createdAt;
  final String? readAt;

  const Notification({
    required this.notificationId,
    required this.userId,
    required this.title,
    required this.body,
    required this.category,
    required this.severity,
    required this.isRead,
    required this.readStatus,
    required this.deliveryStatus,
    this.deliveredAt,
    required this.originType,
    required this.originLabel,
    required this.receiptRequired,
    this.receiptGroupId,
    required this.ackStatus,
    this.ackAt,
    this.ackNote,
    this.relatedEntityType,
    this.relatedEntityId,
    required this.createdAt,
    this.readAt,
  });

  @override
  int get hashCode =>
      notificationId.hashCode ^
      userId.hashCode ^
      title.hashCode ^
      body.hashCode ^
      category.hashCode ^
      severity.hashCode ^
      isRead.hashCode ^
      readStatus.hashCode ^
      deliveryStatus.hashCode ^
      deliveredAt.hashCode ^
      originType.hashCode ^
      originLabel.hashCode ^
      receiptRequired.hashCode ^
      receiptGroupId.hashCode ^
      ackStatus.hashCode ^
      ackAt.hashCode ^
      ackNote.hashCode ^
      relatedEntityType.hashCode ^
      relatedEntityId.hashCode ^
      createdAt.hashCode ^
      readAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Notification &&
          runtimeType == other.runtimeType &&
          notificationId == other.notificationId &&
          userId == other.userId &&
          title == other.title &&
          body == other.body &&
          category == other.category &&
          severity == other.severity &&
          isRead == other.isRead &&
          readStatus == other.readStatus &&
          deliveryStatus == other.deliveryStatus &&
          deliveredAt == other.deliveredAt &&
          originType == other.originType &&
          originLabel == other.originLabel &&
          receiptRequired == other.receiptRequired &&
          receiptGroupId == other.receiptGroupId &&
          ackStatus == other.ackStatus &&
          ackAt == other.ackAt &&
          ackNote == other.ackNote &&
          relatedEntityType == other.relatedEntityType &&
          relatedEntityId == other.relatedEntityId &&
          createdAt == other.createdAt &&
          readAt == other.readAt;
}

/// Mirror of `NotificationListResponse`.
class NotificationList {
  final List<Notification> items;
  final PlatformInt64 total;
  final PlatformInt64 limit;
  final PlatformInt64 offset;

  const NotificationList({
    required this.items,
    required this.total,
    required this.limit,
    required this.offset,
  });

  @override
  int get hashCode =>
      items.hashCode ^ total.hashCode ^ limit.hashCode ^ offset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotificationList &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          total == other.total &&
          limit == other.limit &&
          offset == other.offset;
}

/// Mirror of `NotificationReceipt`.
class NotificationReceipt {
  final String notificationId;
  final String userId;
  final String? title;
  final String originType;
  final String originLabel;
  final String? receiptGroupId;
  final String deliveryStatus;
  final String? deliveredAt;
  final String readStatus;
  final String? readAt;
  final String ackStatus;
  final String? ackAt;
  final String? ackNote;
  final String updatedAt;

  const NotificationReceipt({
    required this.notificationId,
    required this.userId,
    this.title,
    required this.originType,
    required this.originLabel,
    this.receiptGroupId,
    required this.deliveryStatus,
    this.deliveredAt,
    required this.readStatus,
    this.readAt,
    required this.ackStatus,
    this.ackAt,
    this.ackNote,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      notificationId.hashCode ^
      userId.hashCode ^
      title.hashCode ^
      originType.hashCode ^
      originLabel.hashCode ^
      receiptGroupId.hashCode ^
      deliveryStatus.hashCode ^
      deliveredAt.hashCode ^
      readStatus.hashCode ^
      readAt.hashCode ^
      ackStatus.hashCode ^
      ackAt.hashCode ^
      ackNote.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotificationReceipt &&
          runtimeType == other.runtimeType &&
          notificationId == other.notificationId &&
          userId == other.userId &&
          title == other.title &&
          originType == other.originType &&
          originLabel == other.originLabel &&
          receiptGroupId == other.receiptGroupId &&
          deliveryStatus == other.deliveryStatus &&
          deliveredAt == other.deliveredAt &&
          readStatus == other.readStatus &&
          readAt == other.readAt &&
          ackStatus == other.ackStatus &&
          ackAt == other.ackAt &&
          ackNote == other.ackNote &&
          updatedAt == other.updatedAt;
}

/// Mirror of `NotificationReceiptGroup`.
class ReceiptGroup {
  final String receiptGroupId;
  final String? title;
  final String? flightId;
  final String? dispatchOrderId;
  final String? groupId;
  final String originType;
  final String originLabel;
  final bool receiptRequired;
  final ReceiptSummary summary;
  final List<NotificationReceipt> items;

  const ReceiptGroup({
    required this.receiptGroupId,
    this.title,
    this.flightId,
    this.dispatchOrderId,
    this.groupId,
    required this.originType,
    required this.originLabel,
    required this.receiptRequired,
    required this.summary,
    required this.items,
  });

  @override
  int get hashCode =>
      receiptGroupId.hashCode ^
      title.hashCode ^
      flightId.hashCode ^
      dispatchOrderId.hashCode ^
      groupId.hashCode ^
      originType.hashCode ^
      originLabel.hashCode ^
      receiptRequired.hashCode ^
      summary.hashCode ^
      items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiptGroup &&
          runtimeType == other.runtimeType &&
          receiptGroupId == other.receiptGroupId &&
          title == other.title &&
          flightId == other.flightId &&
          dispatchOrderId == other.dispatchOrderId &&
          groupId == other.groupId &&
          originType == other.originType &&
          originLabel == other.originLabel &&
          receiptRequired == other.receiptRequired &&
          summary == other.summary &&
          items == other.items;
}

/// Mirror of `NotificationReceiptSummary`.
class ReceiptSummary {
  final PlatformInt64 totalCount;
  final PlatformInt64 pendingCount;
  final PlatformInt64 acknowledgedCount;
  final PlatformInt64 rejectedCount;
  final String? latestUpdatedAt;

  const ReceiptSummary({
    required this.totalCount,
    required this.pendingCount,
    required this.acknowledgedCount,
    required this.rejectedCount,
    this.latestUpdatedAt,
  });

  @override
  int get hashCode =>
      totalCount.hashCode ^
      pendingCount.hashCode ^
      acknowledgedCount.hashCode ^
      rejectedCount.hashCode ^
      latestUpdatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiptSummary &&
          runtimeType == other.runtimeType &&
          totalCount == other.totalCount &&
          pendingCount == other.pendingCount &&
          acknowledgedCount == other.acknowledgedCount &&
          rejectedCount == other.rejectedCount &&
          latestUpdatedAt == other.latestUpdatedAt;
}
