// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

/// `GET /api/v2/mobile/operations/events`.
Future<OperationsFeed> operationsEvents({required PlatformInt64 limit}) =>
    RustLib.instance.api.crateApiOperationsOperationsEvents(limit: limit);

class OperationsEvent {
  final String eventId;
  final String eventType;
  final String severity;
  final String status;
  final String title;
  final String? flightId;
  final String occurredAt;
  final String source;

  const OperationsEvent({
    required this.eventId,
    required this.eventType,
    required this.severity,
    required this.status,
    required this.title,
    this.flightId,
    required this.occurredAt,
    required this.source,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      eventType.hashCode ^
      severity.hashCode ^
      status.hashCode ^
      title.hashCode ^
      flightId.hashCode ^
      occurredAt.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OperationsEvent &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          eventType == other.eventType &&
          severity == other.severity &&
          status == other.status &&
          title == other.title &&
          flightId == other.flightId &&
          occurredAt == other.occurredAt &&
          source == other.source;
}

class OperationsFeed {
  final String? userId;
  final String? generatedAt;
  final PlatformInt64 total;
  final Map<String, PlatformInt64> eventTypeCounts;
  final Map<String, PlatformInt64> severityCounts;
  final List<OperationsEvent> events;

  const OperationsFeed({
    this.userId,
    this.generatedAt,
    required this.total,
    required this.eventTypeCounts,
    required this.severityCounts,
    required this.events,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      generatedAt.hashCode ^
      total.hashCode ^
      eventTypeCounts.hashCode ^
      severityCounts.hashCode ^
      events.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OperationsFeed &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          generatedAt == other.generatedAt &&
          total == other.total &&
          eventTypeCounts == other.eventTypeCounts &&
          severityCounts == other.severityCounts &&
          events == other.events;
}
