// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'session.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`

/// Restore a persisted bundle at startup. Fail-closed: an obviously invalid
/// bundle (empty token/secret fields) clears the session to anonymous and
/// returns an error instead of silently degrading.
Future<void> restoreTokens({required TokenBundle bundle}) =>
    RustLib.instance.api.crateApiSessionRestoreTokens(bundle: bundle);

/// Current bundle for Dart-side persistence (store after login, clear on
/// logout). `None` when anonymous.
Future<TokenBundle?> currentTokenBundle() =>
    RustLib.instance.api.crateApiSessionCurrentTokenBundle();

/// Stream of token-free session state. Emits the current snapshot
/// immediately, then every transition until the sink is dropped.
Stream<SessionState> sessionState() =>
    RustLib.instance.api.crateApiSessionSessionState();

/// Logout: best-effort server call, local session always cleared (Dart must
/// also delete the persisted bundle).
Future<void> logout() => RustLib.instance.api.crateApiSessionLogout();

@freezed
sealed class SessionState with _$SessionState {
  const SessionState._();

  const factory SessionState.anonymous() = SessionState_Anonymous;
  const factory SessionState.active({required PlatformInt64 accessExpireAt}) =
      SessionState_Active;
}

/// Mirror of `mobile_core::session::TokenBundle`. This exact shape is what
/// Dart stores in flutter_secure_storage after login and hands back via
/// [`restore_tokens`] at startup.
class TokenBundle {
  final String accessToken;
  final String refreshToken;
  final String sessionSecret;
  final PlatformInt64 accessExpireAt;

  const TokenBundle({
    required this.accessToken,
    required this.refreshToken,
    required this.sessionSecret,
    required this.accessExpireAt,
  });

  @override
  int get hashCode =>
      accessToken.hashCode ^
      refreshToken.hashCode ^
      sessionSecret.hashCode ^
      accessExpireAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TokenBundle &&
          runtimeType == other.runtimeType &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken &&
          sessionSecret == other.sessionSecret &&
          accessExpireAt == other.accessExpireAt;
}
