// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `runtime_slot`, `runtime`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CoreRuntime`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`

/// Initialize the core. Must be called once before any other export.
/// Re-initialization is allowed (replaces the previous runtime).
///
/// `operator_context_id` is the stable device id sent as
/// `X-Operator-Context-Id` on every request (§0.3; the legacy app uses
/// ANDROID_ID). It doubles as the `device_id` for device register/heartbeat.
/// `db_path` is the sqlite offline-queue file (Dart:
/// `getApplicationSupportDirectory`).
Future<void> initCore({
  required String baseUrl,
  required bool allowCleartext,
  required String dbPath,
  required String operatorContextId,
}) => RustLib.instance.api.crateApiInitCore(
  baseUrl: baseUrl,
  allowCleartext: allowCleartext,
  dbPath: dbPath,
  operatorContextId: operatorContextId,
);

/// P0 FFI round-trip demo: sign a request with a fresh timestamp and nonce
/// and return the four anti-replay header values.
Future<SignatureHeaders> pingSignDemo({
  required String method,
  required String uri,
  required List<int> body,
  required String secret,
}) => RustLib.instance.api.crateApiPingSignDemo(
  method: method,
  uri: uri,
  body: body,
  secret: secret,
);

/// Connect to the universal SSE stream (`GET /api/v2/sse/stream`, see
/// `sse.rs` docs) and forward every event / connection-state change to Dart
/// until the sink is dropped. The token comes from the restored session.
Stream<SseUpdate> notificationsStream() =>
    RustLib.instance.api.crateApiNotificationsStream();

/// Mirror of `mobile_core::signing::SignatureHeaders` for frb codegen.
/// Kept as a local struct so `mobile-core` stays frb-free.
class SignatureHeaders {
  final String timestamp;
  final String nonce;
  final String bodySha256;
  final String signature;

  const SignatureHeaders({
    required this.timestamp,
    required this.nonce,
    required this.bodySha256,
    required this.signature,
  });

  @override
  int get hashCode =>
      timestamp.hashCode ^
      nonce.hashCode ^
      bodySha256.hashCode ^
      signature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SignatureHeaders &&
          runtimeType == other.runtimeType &&
          timestamp == other.timestamp &&
          nonce == other.nonce &&
          bodySha256 == other.bodySha256 &&
          signature == other.signature;
}

@freezed
sealed class SseConnectionState with _$SseConnectionState {
  const SseConnectionState._();

  const factory SseConnectionState.connecting() = SseConnectionState_Connecting;
  const factory SseConnectionState.connected() = SseConnectionState_Connected;
  const factory SseConnectionState.disconnected({required String reason}) =
      SseConnectionState_Disconnected;
}

/// One SSE event; `data` is the raw JSON payload (parsed on the Dart side).
class SseEvent {
  final String event;
  final String data;

  const SseEvent({required this.event, required this.data});

  @override
  int get hashCode => event.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SseEvent &&
          runtimeType == other.runtimeType &&
          event == other.event &&
          data == other.data;
}

@freezed
sealed class SseUpdate with _$SseUpdate {
  const SseUpdate._();

  const factory SseUpdate.state(SseConnectionState field0) = SseUpdate_State;
  const factory SseUpdate.event(SseEvent field0) = SseUpdate_Event;
}
