// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoleResponse = { id: string, name: string, description: string | null, permissions: Array<string>, is_active: boolean, is_system: boolean, created_at: string, updated_at: string, user_count: bigint, };
