// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Token = { access_token: string, token_type: string, expires_in: bigint, refresh_token: string | null, sse_token: string | null, sse_expires_in: bigint | null, session_secret: string | null, };
