// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TokenData = { sub: string | null, email: string | null, username: string | null, type: string | null, is_admin: boolean | null, permissions: Array<string>, department: string | null, department_id: string | null, pv: bigint | null, iat: bigint | null, exp: bigint | null, iss: string | null, aud: string | null, ua_hash: string | null, ip_subnet_hash: string | null, };
